/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Document;
import EDD.HashTable;
import Funciones.Function;
import Funciones.helpers;
import static Ventanas.Menu.hashTable;
import javax.swing.JOptionPane;

/**
 *
 * @author eliocolmenares
 */
public class BuscarPalabra extends javax.swing.JFrame {

    /**
     * Creates new form BuscarPalabra
     */
    
    public static Menu v2;
     
    public BuscarPalabra(Menu v2) {
        initComponents();
        this.v2 = v2;
        v2.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputPalabraClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buscarClave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado_doc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        inputClaveDoc1 = new javax.swing.JTextField();
        verDetalle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        detalleDoc = new javax.swing.JTextArea();
        volver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 89, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("BUSCAR POR PALABRA CLAVE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 380, 40));
        jPanel1.add(inputPalabraClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, -1));

        jLabel2.setText("Ingresa la palabra que quiera buscar en las palabras claves de los documentos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        buscarClave.setText("Buscar");
        buscarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClaveActionPerformed(evt);
            }
        });
        jPanel1.add(buscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 180, -1));

        resultado_doc.setColumns(20);
        resultado_doc.setRows(5);
        jScrollPane1.setViewportView(resultado_doc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, 120));

        jLabel3.setText("Ingresa la clave del documento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(inputClaveDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, -1));

        verDetalle.setText("Ver completo");
        verDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(verDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 110, -1));

        detalleDoc.setColumns(20);
        detalleDoc.setRows(5);
        jScrollPane2.setViewportView(detalleDoc);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 450, 150));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel4.setText("Ingresa el codigo del documento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        jPanel1.add(inputCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClaveActionPerformed
        Function func = new Function();
        
        if(!hashTable.HashisEmpty()){
        String palabraClave = inputPalabraClave.getText();
        String resultadoBusqueda = func.searchDocumentsByKeyword(hashTable, palabraClave);
            if (resultadoBusqueda.isEmpty()){
                JOptionPane.showMessageDialog(null, "NO EXISTE LA PALABRA EN LOS DOCUMENTOS","ERROR", HEIGHT);
            }else{
                resultado_doc.setText(resultadoBusqueda);
        }
        }else{
            JOptionPane.showMessageDialog(null, "NO HAY DOCUMENTOS CARGADOS","ERROR", HEIGHT);
        }
        
       /* if (resultadoBusqueda.isEmpty()){
            //resultado_doc.setText("No se encuentra la palabra en ningun documento");
            JOptionPane.showMessageDialog(null, "NO EXISTE LA PALABRA EN LOS DOCUMENTOS","ERROR", HEIGHT);
        }else{
            resultado_doc.setText(resultadoBusqueda);
        }*/
    }//GEN-LAST:event_buscarClaveActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
       this.setVisible(false);
        v2.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void verDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetalleActionPerformed
        if(!hashTable.HashisEmpty()){
            String keyString = inputClaveDoc1.getText();
            String codString = inputCod.getText();
        
            helpers help = new helpers();
            if(help.ValidarNumeros(keyString) != -1){
                int key = help.ValidarNumeros(keyString);
                if(help.ValidarNumeros(codString) != -1){
                    int cod = help.ValidarNumeros(codString); 
                    if(hashTable.keyInHash(key)){
                        if(help.validarRangeList(cod, hashTable.getTable()[key].getSize())){
                            Document docResult = hashTable.getDocumentByKeyCod(key, cod);
                            detalleDoc.setText(docResult.toString());
                    
                        }else{
                            JOptionPane.showMessageDialog(null,"El codigo no esta dentro de la lista de documentos correspondiente");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"La clave no se encuentra en el hashTable");
                    }         
                }else{ 
                    JOptionPane.showMessageDialog(null,"El codigo deber ser un numero");     
                }
        
            }else{
                JOptionPane.showMessageDialog(null,"La clave deber ser un numero");
            }
        }else{
           JOptionPane.showMessageDialog(null, "NO HAY DOCUMENTOS CARGADOS","ERROR", HEIGHT); 
        }
                   
    }//GEN-LAST:event_verDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPalabra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPalabra(v2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarClave;
    private javax.swing.JTextArea detalleDoc;
    private javax.swing.JTextField inputClaveDoc1;
    private javax.swing.JTextField inputCod;
    private javax.swing.JTextField inputPalabraClave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultado_doc;
    private javax.swing.JButton verDetalle;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
